# Generated by Django 3.0 on 2019-12-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='date',
        ),
    ]
