# Generated by Django 3.0 on 2019-12-06 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 6, 17, 5, 41, 813011)),
        ),
    ]
